name: Selenium Grid CI

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  selenium-tests:
    runs-on: ubuntu-latest # Use a fresh Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Get your code

      - name: Set up Docker Compose
        run: |
          docker-compose up -d --build # Start Selenium Hub and Nodes in detached mode

      - name: Wait for Selenium Grid to be ready
        run: |
          # A simple wait mechanism, you might need a more robust one for production
          sleep 30 

      - name: Run Selenium Tests
        run: |
          # Replace 'your_test_command_here' with the actual command to run your tests.
          # This could be a command to execute a test runner (e.g., Maven, npm test, pytest).
          # Ensure your tests are configured to connect to the Selenium Hub (localhost:4444).
           mkdir -p TestResults Screenshots
          dotnet test --configuration Release --no-build \
            --logger "trx;LogFileName=TestResults_${{ matrix.browser }}.trx"
      - name: Tear down Docker Compose
        if: always() # Ensure this step runs even if tests fail
        run: |
          docker-compose down # Stop and remove the containers
